### ISSUE TITLE
Jelly Sculk Glowing effect issue

### ISSUE THREAD

**Issue by Flame0015** [Provismet/Provi-Origins#10]
### Type of Error

Incorrect Behaviour

### Description

The glowing effect doesn't seem to detect any mobs while they walk around or get damaged or anything, neither do spectral arrows.

### Mod Version

1.6.2

### Minecraft Version

1.20.2

### Mod Loader

Fabric

### Steps to Reproduce

Simply any mob doing any actions cannot be seen.

**Comment by Provismet** [comment]
Can you provide a video of this behaviour? Everything seems to be working on my end.

Are you using any other mods?

**Comment by Flame0015** [comment]
Yes I was using other mods and I figured out the issue. Something with the **Fantastic Biomes Cave 2.1.3 1.20+ 1.20.4** mod by vanillaPL (Curseforge link https://www.curseforge.com/minecraft/mc-mods/fantastic-biomes-cave) stops mobs from getting the glowing effect. I removed the mod and mobs would get the glowing effect just like normal on pre-existing worlds and new ones.

**Comment by Provismet** [comment]
This issue is caused by another mod, and therefore won't be worked on. You should report this to vanillaPL.
