### ISSUE TITLE
Farmer's delight - Drakling

### ISSUE THREAD

**Issue by Dagslye** [Provismet/Provi-Origins#11]
### Type of Suggestion

Mod Compatibility

### Description

So, I've been playing recently on a server with friends, and one of them picked the Drakling Origin. We're also using Farmer's delight (and somme add ons: End Delight; Nether's delight...), and noticed that most of the food containing meat isn't edible for them, I admit that some dishes don't only contain meat (for example pasta bolognese) , but I still thought it was weird. 

I don't know if this was intended or not, and if it was sorry for the disturbance, but if it wasn't maybe you could give it a look and see if a compatibility is possible?

Thanks for the mod, it's really cool too lol, thanks for your time.

### Reason

I think it would be cool to have more food option with farmer's delight, while still using the carnivorous nature of the drakling and drake.

**Comment by Provismet** [comment]
The Drakling makes use of the base power `origins:carnivore`, this behaviour is not controlled by Provi's Origins, but by Origins itself.

If Farmer's Delight's food isn't compatible then it means one of the following:
1) Farmer's Delight does not correctly tag its food / does not correctly classify it as meat.
2) Origins does not correctly use convention tags.

This problem can be solved for your server by adding the relevant items to the `origins:meat` tag in a basic datapack.

**Comment by Dagslye** [comment]
Oh ok, thanks. I thought it was a special behaviour of your mod, since we had tested another origin mod where someone was some sort of cat? And could only eat fish based dishes from Farmer's delight. Sorry for taking your time, but thanks!

**Comment by Provismet** [comment]
Upon further inspection, Farmer's Delight [does in fact tag correctly](https://github.com/MehVahdJukaar/FarmersDelight/blob/1.20/src/generated/resources/data/origins/tags/items/meat.json). Check that you are using the Refabricated version by Pug.

**Comment by Dagslye** [comment]
We are using the Refabricated version indeed, apparently some of the food isn't marked as carnivorous, I guess it's a choice from the dev then. Thanks again, I think i'm going to change it to include more foods.
