### ISSUE TITLE
CraftTweaker Incompatibility

### ISSUE THREAD

**Issue by MelodyMcKenna** [Provismet/Provi-Origins#2]
### Type of Error

Incorrect Behaviour

### Mod List

- provi-origins-1.4.1
- CraftTweaker-fabric-1.20.1-14.0.12

### Description

Four errors show up in chat upon login. This happens in both single-player and on a server and only when both of the above mods are installed.
![image](https://github.com/Provismet/Provi-Origins/assets/29812480/12323373-96f3-4ccd-a41b-8aa1b7873481)

There are no active scripts for CraftTweaker in my single player world where this screenshot was taken.

### Mod Version

provi-origins-1.4.1 and 1.4.0

### Minecraft Version

1.19.4

### Mod Loader

Fabric

### Steps to Reproduce

```bash
Minecraft Version 1.20.1 (version 1.19.4 was the only option above)

Install both Provi Origins version 1.4.1 and CraftTweaker version 14.0.12 on the client and server if applicable.

Launch the game and login to a single player world or server.

The errors show upon login.
```

### Crash Log

```bash
No crash report
```

**Comment by Provismet** [comment]
I highly recommend also submitting a similar issue to the [CraftTweaker](https://github.com/CraftTweaker/CraftTweaker/issues) issues page as this is likely a problem on their end (reasoning below).

I have, however, managed to fix the issue and will bundle this fix with the next big update to the mod, which should be soon.

Why I believe this is on CraftTweaker's side and should be reported over there:  
Fixing this issue involved simply replacing an inner-static Invoker mixin with a `@Shadow` field. This really shouldn't affect anything. My best guess would be that CraftTweaker changes mixin loading in a way that breaks Invokers from inner-static classes, but the lack of a more detailed error prevents me from knowing *why* that is.

**Comment by MelodyMcKenna** [comment]
Thank you. I appreciate you getting to this so quickly. I'll be sure to report this to CraftTweaker as well.
