### ISSUE TITLE
Clones Crash (1.20.1)

### ISSUE THREAD

**Issue by Lunatrixen** [Provismet/Provi-Origins#8]
### Type of Error

Crash

### Description

As friend described it: Occurred after someone had died resulting in the both of them becoming chunk banned.

[crash-2024-07-03_00.24.49-client.txt](https://github.com/user-attachments/files/16077129/crash-2024-07-03_00.24.49-client.txt)

### Mod Version

1.5.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

```bash
Unfortunately it seems to happen randomly.
```

### Crash Log

```bash
In description
```

**Comment by Provismet** [comment]
Thank you for the report. Based on your crash log this appears to be happening because the Clone renderer is failing to get its owner from the player list.

Not sure why this is happening, but I can implement a stop-gap solution for it.
